name: Integration Test
on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  integration_test:
    name: Integration Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.release.tag_name }}
      - name: Create Feedstock meta
        id: create-feedstock-meta
        uses: ./
        with:
          project: "featuretools"
          pypi_version: "v1.11.1"
          setup_cfg_filepath: "create_feedstock_meta_yaml/test_setup.cfg"
          meta_yaml_filepath: "create_feedstock_meta_yaml/test_meta.yaml"
          test_reqs_to_add: "graphviz !=2.47.2"
      - name: Print output
        run: cat example_meta.yaml
